# ETL Pipeline Preparation
Follow the instructions below to help you create your ETL pipeline.
### 1. Import libraries and load datasets.
- Import Python libraries
- Load `messages.csv` into a dataframe and inspect the first few lines.
- Load `categories.csv` into a dataframe and inspect the first few lines.

In [1]:
# import libraries
import pandas as pd
from time import time

from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool
#import re
import udacourse2 #my library!
import math

In [2]:
gen_begin = time()

# load messages dataset
messages = pd.read_csv('messages.csv', index_col='id')
#messages['id'] = messages.index
#messages.info()
#messages.index
messages.head()

message  \
id                                                      
2   Weather update - a cold front from Cuba that c...   
7             Is the Hurricane over or is it not over   
8                     Looking for someone but no name   
9   UN reports Leogane 80-90 destroyed. Only Hospi...   
12  says: west side of Haiti, rest of the country ...   

                                             original   genre  
id                                                             
2   Un front froid se retrouve sur Cuba ce matin. ...  direct  
7                  Cyclone nan fini osinon li pa fini  direct  
8   Patnm, di Maryani relem pou li banm nouvel li ...  direct  
9   UN reports Leogane 80-90 destroyed. Only Hospi...  direct  
12  facade ouest d Haiti et le reste du pays aujou...  direct

In [3]:
# load categories dataset
categories = pd.read_csv('categories.csv', index_col='id')
#categories.info()
categories.head()

categories
id                                                   
2   related-1;request-0;offer-0;aid_related-0;medi...
7   related-1;request-0;offer-0;aid_related-1;medi...
8   related-1;request-0;offer-0;aid_related-0;medi...
9   related-1;request-1;offer-0;aid_related-1;medi...
12  related-1;request-0;offer-0;aid_related-0;medi...

### 6. Remove duplicates.
- Check how many duplicates are in this dataset.
- Drop the duplicates.
- Confirm duplicates were removed
- Index duplicated [here](https://stackoverflow.com/questions/35084071/concat-dataframe-reindexing-only-valid-with-uniquely-valued-index-objects)

In [4]:
#messages.index.duplicated(keep='first')
#drop index duplicated messages
messages = messages.loc[~messages.index.duplicated(keep='first')]

In [5]:
#check number of remaining duplicated messages
print(messages[messages.duplicated()].shape[0])
#drop duplicates
messages = messages.drop_duplicates()
print(messages.shape[0])
# check number of duplicates
messages[messages.duplicated()].shape[0]

3
26177


0

### 2. Merge datasets.
- Merge the messages and categories datasets using the common id
- Assign this combined dataset to `df`, which will be cleaned in the following steps

- used SQL-type of relations, having the messages dataframe as refference
- documentation [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

In [6]:
# merge datasets
df = pd.merge(messages, categories, left_index=True, right_index=True, how='left')
print(df.shape[0])
df.name = 'df'
df.head()

26245


message  \
id                                                      
2   Weather update - a cold front from Cuba that c...   
7             Is the Hurricane over or is it not over   
8                     Looking for someone but no name   
9   UN reports Leogane 80-90 destroyed. Only Hospi...   
12  says: west side of Haiti, rest of the country ...   

                                             original   genre  \
id                                                              
2   Un front froid se retrouve sur Cuba ce matin. ...  direct   
7                  Cyclone nan fini osinon li pa fini  direct   
8   Patnm, di Maryani relem pou li banm nouvel li ...  direct   
9   UN reports Leogane 80-90 destroyed. Only Hospi...  direct   
12  facade ouest d Haiti et le reste du pays aujou...  direct   

                                           categories  
id                                                     
2   related-1;request-0;offer-0;aid_related-0;medi...  
7   related-1;request-0;offer-0;aid_related-1;medi...  
8   related-1;request-0;offer-0;aid_related-0;medi...  
9   related-1;request-1;offer-0;aid_related-1;medi...  
12  related-1;request-0;offer-0;aid_related-0;medi...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26245 entries, 2 to 30265
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   message     26245 non-null  object
 1   original    10184 non-null  object
 2   genre       26245 non-null  object
 3   categories  26245 non-null  object
dtypes: object(4)
memory usage: 1.0+ MB


### 3. Split `categories` into separate category columns.
- Split the values in the `categories` column on the `;` character so that each value becomes a separate column. You'll find [this method](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.str.split.html) very helpful! Make sure to set `expand=True`.
- Use the first row of categories dataframe to create column names for the categories data.
- Rename columns of `categories` with new column names.

Solution [here](https://stackoverflow.com/questions/42049147/convert-list-to-pandas-dataframe-column)

In [8]:
# create a dataframe of the 36 individual category columns
jumber = df['categories'].iloc[0]
categories = jumber.split(sep=';')
#{'categories': categories}
categories = pd.DataFrame({'categories': categories})
categories.head()

categories
0       related-1
1       request-0
2         offer-0
3   aid_related-0
4  medical_help-0

In [9]:
# select the first row of the categories dataframe
row = categories.iloc[0]
row['categories'][:-2]

[cat[:-2] for cat in categories['categories']]

# use this row to extract a list of new column names for categories.
# one way is to apply a lambda function that takes everything 
# up to the second to last character of each string with slicing
category_colnames = [cat[:-2] for cat in categories['categories']]
print(category_colnames)

# rename the columns of `categories`
#categories.columns = category_colnames
#categories.head()

['related', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report']


An alert flag, if there was no category inserted:

In [10]:
df['if_blank'] = False

In [11]:
#adding new columns with zero value
for colname in category_colnames:
    df[colname] = 0

#df.columns
print('new shape:',df.shape[1])
#df.head(1)

new shape: 41


In [12]:
cell = df['categories'].iloc[0]
alfa = set(cell.split(sep=';'))
alfa

for beta in alfa:
    if beta.find('1') != -1:
        print(beta[:-2])

related


### 4. Convert category values to just numbers 0 or 1.
- Iterate through the category columns in df to keep only the last character of each string (the 1 or 0). For example, `related-0` becomes `0`, `related-1` becomes `1`. Convert the string to a numeric value.
- You can perform [normal string actions on Pandas Series](https://pandas.pydata.org/pandas-docs/stable/text.html#indexing-with-str), like indexing, by including `.str` after the Series. You may need to first convert the Series to be of type string, which you can do with `astype(str)`.

In [13]:
begin = time()

filtered_cols = ['categories', 'if_blank', 'related', 'request', 'offer', 'aid_related', 'medical_help', 
       'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 
       'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 
       'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 
       'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report']

df[filtered_cols] = df[filtered_cols].apply(lambda x: udacourse2.fn_test(x, verbose=True), axis=1)

spent = time() - begin
print('elapsed time: {:.1f}s ({}min, {:.4f}sec)'.format(spent, math.trunc((spent)/60), math.fmod(spent, 60)))
#df.head()

###
related
###
weather_related
other_aid
aid_related
storm
related
###
related
###
medical_products
other_aid
buildings
hospitals
aid_related
infrastructure_related
related
request
###
related
###
*empty element*
###
weather_related
storm
related
###
direct_report
aid_related
related
request
shelter
water
###
*empty element*
###
medical_products
direct_report
medical_help
aid_related
related
request
###
weather_related
medical_products
other_aid
buildings
direct_report
other_infrastructure
medical_help
aid_related
infrastructure_related
related
food
floods
request
transport
water
###
*empty element*
###
direct_report
aid_related
related
request
water
###
direct_report
aid_related
related
food
request
###
related
###
medical_products
direct_report
clothing
aid_related
related
food
request
shelter
water
###
direct_report
medical_help
aid_related
related
food
request
water
###
*empty element*
###
*empty element*
###
weather_related
earthquake
related
###
related
###
other_aid
direct_repo

food
request
water
###
*empty element*
###
related
###
other_aid
direct_report
aid_related
related
request
###
direct_report
aid_related
related
food
request
water
###
*empty element*
###
related
###
weather_related
direct_report
aid_related
related
food
shops
request
shelter
other_weather
water
infrastructure_related
###
direct_report
aid_related
related
food
request
water
###
direct_report
aid_related
related
food
request
###
*empty element*
###
direct_report
related
###
related
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
aid_related
related
food
###
*empty element*
###
aid_related
related
money
###
direct_report
aid_related
related
request
water
###
weather_related
other_aid
direct_report
medical_help
aid_related
related
floods
request
transport
###
other_aid
direct_report
aid_related
related
food
search_and_rescue
request
water
###
direct_report
aid_related
related
food
request
shelter
###
direct_report
aid_related
related
request
water
###
offer

aid_related
related
food
request
###
weather_related
refugees
hospitals
aid_related
infrastructure_related
cold
related
security
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
other_aid
refugees
aid_related
related
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
related
request
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
direct_report
aid_related
related
food
request
###
weather_related
other_aid
direct_report
medical_help
aid_related
related
floods
request
transport
###
buildings
direct_report
medical_help
aid_related
related
food
request
water
###
*empty element*
###
related
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
medical_products
direct_report
clothing
medical_help
aid_related
related
food
request
shelter
death
water
###
other_aid
aid_related
related
###
*empty element*
###
direct_report
aid_related
related
request
shelter
###
*empty element*
###
medical

money
###
direct_report
aid_related
related
food
request
water
###
direct_report
aid_related
related
food
request
water
###
medical_products
medical_help
aid_related
related
death
###
medical_products
other_aid
direct_report
aid_related
related
food
security
request
shelter
water
###
direct_report
aid_related
related
food
request
shelter
###
direct_report
aid_related
related
search_and_rescue
request
death
###
weather_related
earthquake
buildings
direct_report
medical_help
aid_related
related
request
shelter
###
missing_people
direct_report
aid_related
related
request
###
direct_report
aid_related
related
food
request
shelter
###
weather_related
earthquake
buildings
direct_report
medical_help
aid_related
related
security
###
*empty element*
###
*empty element*
###
related
###
weather_related
other_aid
other_infrastructure
aid_related
infrastructure_related
related
other_weather
###
direct_report
aid_related
related
food
request
shelter
water
###
buildings
direct_report
aid_related
rela

water
###
related
###
aid_related
related
request
water
###
related
###
direct_report
other_infrastructure
aid_related
infrastructure_related
related
food
request
death
###
buildings
direct_report
refugees
aid_related
related
request
shelter
death
###
direct_report
other_infrastructure
aid_related
infrastructure_related
related
food
request
###
other_aid
direct_report
aid_related
related
request
shelter
###
related
###
weather_related
direct_report
other_infrastructure
aid_centers
aid_related
infrastructure_related
related
food
search_and_rescue
request
electricity
other_weather
###
related
###
medical_products
direct_report
clothing
aid_related
related
food
request
###
related
###
other_aid
direct_report
aid_related
related
request
###
other_aid
direct_report
aid_related
related
food
request
###
other_aid
direct_report
aid_related
related
request
water
###
direct_report
refugees
aid_related
related
request
###
direct_report
aid_related
related
food
request
death
###
weather_related
ea

food
floods
request
death
water
###
direct_report
related
###
weather_related
fire
direct_report
medical_help
aid_related
related
search_and_rescue
request
electricity
water
###
other_aid
direct_report
refugees
aid_related
related
request
###
other_aid
buildings
direct_report
aid_related
related
food
request
shelter
water
###
related
###
weather_related
missing_people
other_aid
aid_related
related
floods
search_and_rescue
request
transport
###
other_aid
direct_report
aid_related
related
request
shelter
###
direct_report
aid_related
related
food
request
###
other_aid
direct_report
aid_related
related
request
###
other_aid
direct_report
aid_related
related
request
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
other_aid
direct_report
aid_related
related
food
request
shelter
electricity
###
direct_report
aid_related
related
food
request
###
direct_report
aid_related
related
food
request
###
*empty element*
###
related
###
other_aid
direct_report
aid_relate

###
other_aid
direct_report
aid_related
related
###
weather_related
earthquake
direct_report
aid_related
related
food
request
water
###
weather_related
earthquake
direct_report
medical_help
aid_related
related
floods
transport
###
*empty element*
###
other_aid
aid_related
related
request
###
other_aid
direct_report
aid_related
related
request
###
other_aid
aid_related
related
security
###
weather_related
earthquake
other_aid
aid_related
related
request
###
other_aid
direct_report
aid_related
related
request
###
weather_related
earthquake
aid_related
related
death
###
*empty element*
###
direct_report
aid_related
related
food
request
shelter
###
weather_related
direct_report
aid_related
infrastructure_related
related
food
shops
security
request
other_weather
water
###
weather_related
medical_products
military
other_aid
direct_report
aid_related
cold
related
request
transport
###
other_aid
aid_related
related
request
###
buildings
aid_related
related
request
shelter
###
*empty element*
#

related
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
###
weather_related
earthquake
direct_report
related
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
related
###
direct_report
aid_related
related
food
request
###
weather_related
earthquake
related
###
weather_related
medical_products
other_aid
buildings
direct_report
other_infrastructure
medical_help
aid_related
storm
related
request
shelter
other_weather
infrastructure_related
###
weather_related
earthquake
direct_report
related
###
*empty element*
###
*empty element*
###
direct_report
related
request
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
water
###
related
request
###
direct_report
aid_related
related
food
search_and_rescue
request
shelter
water
###
direct_report
aid_related
related
food
request
shelter
water
###
related
###
*empty element

###
weather_related
earthquake
related
###
other_aid
direct_report
aid_related
related
request
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
direct_report
related
request
###
*empty element*
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
related
###
direct_report
related
request
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
direct_report
aid_related
related
request
water
###
direct_report
related
###
*empty element*
###
related
###
other_aid
direct_report
aid_related
related
###
related
###
aid_related
related
security
request
###
*empty element*
###
related
###
direct_report
related
request
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
shelter
water
###
*empty element*
###
direct_report
refugees
aid_related
related
request
###
related
###
related
request
###
weather_related
fire
direct_report
related
###
*empty element*
###
medical_products


###
medical_products
direct_report
medical_help
aid_related
related
food
request
water
###
other_aid
direct_report
aid_related
related
request
###
other_aid
direct_report
medical_help
aid_related
related
request
###
related
###
*empty element*
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
search_and_rescue
request
###
other_aid
direct_report
aid_related
related
request
###
direct_report
aid_related
related
food
request
###
direct_report
aid_related
related
food
request
shelter
water
###
direct_report
aid_related
related
food
request
water
###
related
request
###
aid_related
related
search_and_rescue
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
related
###
*empty element*
###
weather_related
medical_products
buildings
aid_related
storm
related
death
###
*empty element*
###
direct_report
aid_related
related
food
request
###
*empty ele

direct_report
medical_help
aid_related
related
request
###
*empty element*
###
related
request
###
direct_report
aid_related
related
food
request
shelter
###
buildings
aid_related
related
shelter
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
request
###
related
###
weather_related
earthquake
related
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
search_and_rescue
request
shelter
###
*empty element*
###
*empty element*
###
weather_related
earthquake
direct_report
related
###
related
###
military
direct_report
aid_related
related
###
other_aid
direct_report
aid_related
related
request
###
related
###
related
###
*empty element*
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
weather_related
medical_products
earthquake
buildings
direct_report
aid_related
related
request
###
medical_products
direct_report
aid_related
related
food
request
electricity
water
###
related
###
*empty element*
###
other_aid
a

related
request
death
###
direct_report
related
###
related
request
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
shelter
water
money
###
direct_report
aid_related
related
request
water
###
direct_report
aid_related
related
food
request
###
weather_related
earthquake
direct_report
related
request
###
missing_people
direct_report
aid_related
related
###
direct_report
clothing
aid_related
related
food
request
###
direct_report
aid_related
related
food
request
###
*empty element*
###
*empty element*
###
other_aid
buildings
direct_report
aid_related
related
request
death
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
request
###
weather_related
earthquake
other_aid
aid_related
related
request
###
weather_related
earthquake
missing_people
other_aid
aid_related
related
request
money
###
*empty element*
###
*empty element*
###
direct_report
medical_help
aid_related
related
request
shelter
death
###
direct_report
related


###
weather_related
earthquake
other_aid
direct_report
aid_related
related
electricity
###
direct_report
clothing
aid_related
related
request
shelter
###
related
###
direct_report
aid_related
related
food
request
###
direct_report
aid_related
related
request
shelter
###
other_aid
direct_report
aid_related
related
request
###
other_aid
aid_related
related
request
###
related
###
*empty element*
###
direct_report
aid_related
related
request
water
###
other_aid
direct_report
aid_related
related
request
###
direct_report
other_infrastructure
medical_help
aid_related
related
security
request
shelter
infrastructure_related
###
*empty element*
###
weather_related
earthquake
buildings
direct_report
clothing
hospitals
aid_related
related
request
shelter
infrastructure_related
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
request
###
other_aid
direct_report
aid_related
related
request
shelter
###
other_aid
buildings
aid_related
related
shelter
###
direct_report
relat

###
weather_related
direct_report
aid_related
related
request
shelter
other_weather
###
related
request
###
related
###
related
###
*empty element*
###
direct_report
aid_related
related
food
request
###
medical_products
direct_report
aid_related
related
food
request
###
weather_related
direct_report
aid_related
storm
related
request
shelter
###
related
###
related
###
related
###
aid_related
related
request
death
###
*empty element*
###
weather_related
fire
direct_report
refugees
aid_related
related
food
request
shelter
###
direct_report
aid_related
related
food
request
water
###
other_aid
direct_report
medical_help
aid_related
related
food
search_and_rescue
request
###
direct_report
aid_centers
aid_related
infrastructure_related
related
food
request
water
###
aid_related
related
food
request
shelter
###
related
###
clothing
aid_related
related
food
request
shelter
###
related
###
direct_report
aid_related
related
food
search_and_rescue
request
shelter
water
###
*empty element*
###
dir

aid_related
related
food
request
death
###
*empty element*
###
*empty element*
###
related
###
direct_report
aid_related
related
food
request
shelter
water
###
weather_related
earthquake
other_aid
aid_related
related
###
direct_report
aid_related
related
search_and_rescue
###
weather_related
medical_products
direct_report
refugees
aid_related
storm
related
request
shelter
transport
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
shelter
###
direct_report
aid_related
related
food
request
###
related
###
related
###
medical_products
aid_centers
hospitals
medical_help
aid_related
infrastructure_related
related
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
search_and_rescue
request
###
*empty element*
###
direct_report
aid_related
related
request
water
###
weather_related
earthquake
other_aid
direct_report
refugees
aid_related
related
request
###
hospitals
medical_help
aid_related
infrastructure_related
related
###
rel

###
medical_products
medical_help
aid_related
related
request
electricity
transport
###
related
###
*empty element*
###
buildings
aid_related
related
shelter
###
*empty element*
###
direct_report
aid_related
related
food
request
###
*empty element*
###
*empty element*
###
other_aid
aid_related
related
electricity
###
related
###
other_aid
aid_related
related
###
other_aid
direct_report
medical_help
aid_related
related
request
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
medical_help
aid_related
related
###
other_aid
direct_report
aid_related
related
request
###
buildings
direct_report
aid_related
related
food
request
shelter
###
direct_report
medical_help
aid_related
related
food
request
###
related
###
related
###
medical_help
aid_related
related
request
###
related
###
related
###
weather_related
fire
earthquake
direct_report
aid_related
storm
cold
related
food
floods
request
shelter
other_weather
water
###
weather_related
direct_report
aid_related
re

related
food
request
water
###
direct_report
aid_related
related
food
request
water
###
related
###
*empty element*
###
*empty element*
###
direct_report
medical_help
aid_related
related
food
request
###
medical_products
direct_report
aid_related
related
food
request
shelter
water
###
related
###
other_aid
direct_report
aid_related
related
request
money
###
other_aid
aid_related
related
request
###
aid_related
related
food
###
aid_related
related
food
###
direct_report
aid_related
related
food
###
other_aid
direct_report
aid_related
related
food
request
###
offer
weather_related
medical_products
medical_help
aid_related
related
floods
transport
###
related
###
related
###
related
###
related
###
related
###
related
###
direct_report
aid_related
related
food
request
###
*empty element*
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
*empty element*
###
related
###
direct_report
aid_related
related
food
request
water
###
other_aid
aid_r

###
related
###
weather_related
earthquake
other_aid
direct_report
refugees
medical_help
aid_related
related
food
request
death
water
###
other_aid
direct_report
aid_related
related
food
request
death
money
###
direct_report
aid_related
related
food
request
water
###
other_aid
direct_report
refugees
aid_related
related
request
shelter
###
direct_report
aid_related
related
food
request
shelter
water
###
weather_related
direct_report
medical_help
aid_related
related
floods
request
transport
water
###
*empty element*
###
*empty element*
###
*empty element*
###
weather_related
earthquake
buildings
direct_report
medical_help
aid_related
related
food
request
###
direct_report
aid_related
related
request
water
###
*empty element*
###
*empty element*
###
weather_related
medical_products
missing_people
other_aid
refugees
aid_related
related
floods
security
request
transport
###
aid_related
related
food
request
###
related
###
*empty element*
###
weather_related
direct_report
medical_help
aid_re

aid_centers
aid_related
infrastructure_related
related
food
request
###
aid_related
related
food
request
###
*empty element*
###
direct_report
related
###
direct_report
aid_related
related
food
request
shelter
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
request
shelter
###
direct_report
aid_related
related
food
request
###
related
###
weather_related
buildings
direct_report
aid_related
related
food
request
shelter
other_weather
###
other_aid
medical_help
aid_related
related
food
money
###
related
###
direct_report
aid_related
related
food
request
###
related
###
direct_report
aid_related
related
food
request
###
other_aid
direct_report
aid_related
related
request
electricity
###
direct_report
aid_related
related
food
request
###
other_aid
direct_report
aid_related
related
request
###
other_aid
aid_related
related
food
request
###
other_aid
direct_report
aid_related
related
food
request
###
aid_related
related
security
request
###
*e

###
direct_report
aid_related
related
request
shelter
###
related
###
related
###
buildings
direct_report
aid_related
related
food
###
*empty element*
###
related
###
direct_report
related
###
*empty element*
###
related
###
direct_report
aid_related
related
food
security
request
shelter
###
weather_related
direct_report
aid_related
cold
related
request
shelter
###
*empty element*
###
aid_related
related
food
request
###
*empty element*
###
related
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
direct_report
aid_related
related
food
request
money
###
related
###
related
###
related
###
other_aid
direct_report
refugees
aid_related
related
request
###
related
###
buildings
direct_report
aid_related
related
request
shelter
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
direct_report
related
###
related
###
*empty element*
###
*empty element*
###
aid_related
related
request
shelter
###
related
###
*empty elem

other_weather
###
related
###
aid_related
related
food
request
###
related
###
*empty element*
###
weather_related
medical_products
earthquake
other_aid
direct_report
medical_help
aid_related
related
request
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
###
aid_related
related
food
request
###
*empty element*
###
weather_related
medical_products
other_aid
buildings
direct_report
other_infrastructure
medical_help
aid_related
storm
related
food
floods
request
shelter
electricity
other_weather
transport
infrastructure_related
###
direct_report
hospitals
aid_related
infrastructure_related
related
request
money
###
direct_report
related
request
###
direct_report
medical_help
aid_related
infrastructure_related
related
food
shops
request
water
###
related
###
direct_report
aid_related
related
food
request
shelter
###
direct_report
related

request
shelter
###
*empty element*
###
weather_related
earthquake
direct_report
aid_related
related
food
request
shelter
water
###
*empty element*
###
weather_related
earthquake
related
###
weather_related
direct_report
aid_related
storm
related
request
shelter
###
*empty element*
###
related
###
related
###
other_aid
aid_related
related
request
###
direct_report
aid_related
related
food
request
shelter
water
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
buildings
direct_report
related
request
###
other_aid
direct_report
aid_related
related
request
###
direct_report
medical_help
aid_related
related
request
###
related
###
aid_related
related
request
shelter
###
related
###
*empty element*
###
other_aid
aid_related
related
request
###
*empty element*
###
*empty element*
###
weather_related
earthquake
related
###
related
###
*empty element*
###
direct_report
aid_related
related
food
request
shelter
water
###
other_aid
direct_report
aid_related
related
r

*empty element*
###
weather_related
earthquake
related
###
*empty element*
###
weather_related
earthquake
missing_people
other_aid
direct_report
aid_related
related
search_and_rescue
request
###
*empty element*
###
*empty element*
###
related
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
money
###
related
###
*empty element*
###
direct_report
aid_related
related
food
request
###
direct_report
medical_help
aid_related
related
request
water
###
*empty element*
###
other_aid
direct_report
medical_help
aid_related
related
food
request
shelter
###
*empty element*
###
direct_report
aid_related
related
request
shelter
###
direct_report
aid_related
related
request
shelter
water
###
*empty element*
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
direct_report
aid_related
related
food
request
shelter
###
*empty element*
###
other_aid
direct_report
other_infrastructure


direct_report
aid_related
related
request
###
weather_related
medical_products
missing_people
other_aid
direct_report
refugees
medical_help
aid_related
related
floods
search_and_rescue
request
death
transport
water
###
*empty element*
###
*empty element*
###
weather_related
direct_report
aid_related
storm
related
request
shelter
other_weather
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
request
shelter
###
*empty element*
###
*empty element*
###
other_aid
aid_related
related
food
request
shelter
###
direct_report
aid_related
related
food
request
death
water
###
direct_report
aid_related
related
water
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
related
request
###
aid_related
related
food
request
shelter
water
###
other_aid
direct_report
aid_related
related
request
###
other_

direct_report
aid_related
related
request
electricity
###
related
###
other_aid
direct_report
aid_related
related
request
###
weather_related
direct_report
medical_help
aid_related
related
floods
request
shelter
transport
###
related
###
direct_report
aid_related
related
food
request
shelter
water
###
direct_report
related
request
###
related
###
related
###
related
###
*empty element*
###
weather_related
earthquake
direct_report
aid_related
related
food
shops
security
request
shelter
water
infrastructure_related
###
direct_report
aid_related
related
request
shelter
###
*empty element*
###
related
###
missing_people
aid_related
related
request
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
related
###
related
###
*empty element*
###
direct_report
aid_related
related
food
request
###
weather_related
earthquake
other_aid
direct_report
aid_related
storm
cold
related
request
###
weather_related
direct_report
medical_help
aid_related
related
food
floods
requ

direct_report
aid_related
related
request
shelter
###
*empty element*
###
aid_related
related
food
request
shelter
water
###
other_aid
aid_related
related
request
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
shelter
water
###
related
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
request
water
###
*empty element*
###
related
###
aid_related
related
shelter
###
related
###
weather_related
earthquake
direct_report
related
###
related
###
missing_people
aid_related
related
request
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
related
###
related
###
related
###
*empty element*
###
weather_related
other_aid
direct_report
clothing
aid_related
storm
related
request
shelter
###
direct_report
aid_related
related
request
shelter
###
weather_related
direct_report
aid_related
storm
related
request
she

###
related
###
*empty element*
###
aid_related
related
request
money
###
*empty element*
###
direct_report
aid_related
related
request
shelter
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
weather_related
direct_report
refugees
aid_related
storm
related
request
shelter
###
other_aid
aid_related
related
request
shelter
###
*empty element*
###
*empty element*
###
direct_report
related
###
direct_report
aid_related
related
food
request
###
other_aid
direct_report
aid_related
related
request
shelter
electricity
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
request
shelter
###
related
###
weather_related
earthquake
other_aid
aid_related
related
###
related
###
*empty element*
###
related
###
direct_report
related
request
###
direct_report
related
###
direct_report
aid_related
related
request
shelter
###
direct_report
aid_related
related
request
shelter
###
weather_related
direct_report
clothing
aid_re

###
*empty element*
###
related
###
*empty element*
###
related
###
weather_related
other_aid
direct_report
aid_related
storm
related
floods
request
shelter
###
weather_related
military
direct_report
medical_help
aid_related
related
other_weather
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
related
###
weather_related
other_aid
aid_related
storm
related
request
shelter
###
weather_related
direct_report
aid_related
storm
related
request
shelter
###
direct_report
related
request
###
direct_report
related
request
###
*empty element*
###
weather_related
direct_report
aid_related
storm
related
request
shelter
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
###
weather_related
storm
related
###
weather_related
storm
related
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
weather_related
direct_rep

related
###
weather_related
earthquake
aid_related
related
search_and_rescue
request
death
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
related
###
buildings
direct_report
aid_related
related
shelter
###
weather_related
earthquake
direct_report
aid_related
related
death
###
*empty element*
###
related
###
direct_report
related
request
###
related
###
related
###
weather_related
earthquake
direct_report
hospitals
medical_help
aid_related
infrastructure_related
related
request
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
weather_related
direct_report
medical_help
aid_related
related
floods
request
transport
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
water
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
*empty eleme

aid_centers
aid_related
related
food
shops
request
shelter
infrastructure_related
###
related
###
missing_people
other_aid
aid_related
related
request
###
direct_report
aid_related
related
food
request
###
direct_report
aid_related
related
food
request
###
*empty element*
###
*empty element*
###
weather_related
earthquake
related
###
weather_related
earthquake
direct_report
related
###
weather_related
aid_related
storm
related
food
shelter
###
*empty element*
###
related
###
weather_related
direct_report
aid_related
storm
related
request
shelter
###
weather_related
earthquake
direct_report
aid_related
related
death
###
other_aid
direct_report
aid_centers
aid_related
infrastructure_related
related
request
###
*empty element*
###
direct_report
related
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
other_aid
direct_report
refugees
aid_related
related
food
request
shelter
death
###
direct_report
aid_related
related
food
request
shelter
water
###
weather_related

*empty element*
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
weather_related
earthquake
related
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
*empty element*
###
direct_report
related
request
###
related
###
*empty element*
###
buildings
direct_report
aid_related
related
request
shelter
###
related
###
*empty element*
###
*empty element*
###
aid_centers
refugees
aid_related
related
shelter
infrastructure_related
###
*empty element*
###
*empty element*
###
related
###
*empty element*
###
related
###
related
###
direct_report
aid_related
related
request
money
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
weather_related
missing_people
medical_help
aid_related
related
floods
search_and_rescue
death
transport
###
*empty element*
###
*empty element*
###
*empty element*
##

###
*empty element*
###
weather_related
earthquake
related
###
*empty element*
###
*empty element*
###
weather_related
storm
related
other_weather
###
related
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
request
shelter
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
other_aid
aid_related
related
request
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
###
weather_related
earthquake
direct_report
related
###
*empty element*
###
weather_related
earthquake
related
###
direct_report
aid_related
related
food
request
###
*empty element*
###
related
###
*empty element*
###
related
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
related
request
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
*empty element*
#

direct_report
aid_related
related
food
request
###
*empty element*
###
weather_related
earthquake
direct_report
related
other_weather
###
*empty element*
###
aid_related
related
request
shelter
###
direct_report
related
request
###
direct_report
aid_related
related
request
water
###
related
###
weather_related
earthquake
related
###
direct_report
related
request
###
*empty element*
###
direct_report
aid_related
related
shelter
###
aid_related
related
food
request
###
weather_related
earthquake
related
###
weather_related
direct_report
aid_related
storm
related
request
shelter
###
weather_related
military
direct_report
refugees
aid_related
storm
related
request
shelter
###
*empty element*
###
*empty element*
###
related
###
other_aid
direct_report
aid_related
related
request
###
*empty element*
###
*empty element*
###
weather_related
earthquake
related
###
related
###
related
###
related
###
related
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
request
###
w

related
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
request
shelter
###
weather_related
earthquake
other_aid
direct_report
aid_related
related
###
*empty element*
###
weather_related
earthquake
related
###
*empty element*
###
weather_related
earthquake
related
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
request
water
###
*empty element*
###
*empty element*
###
*empty element*
###
weather_related
storm
related
###
*empty element*
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
food
request
###
weather_related
earthquake
related
###
*empty element*
###
aid_related
related
water
###
*empty element*
###
*empty element*
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
related
request
###
direct_report
medical_help
aid_related
related
request
###
related
###
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
related
###
weathe

infrastructure_related
related
floods
shops
search_and_rescue
security
death
transport
###
weather_related
earthquake
related
###
weather_related
earthquake
other_aid
aid_related
related
request
###
weather_related
earthquake
aid_related
tools
cold
related
search_and_rescue
money
###
weather_related
earthquake
related
###
weather_related
other_aid
other_infrastructure
medical_help
aid_related
infrastructure_related
related
request
other_weather
money
###
weather_related
medical_products
earthquake
hospitals
aid_related
infrastructure_related
tools
cold
related
###
related
###
weather_related
earthquake
other_aid
aid_related
related
money
###
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
other_aid
aid_related
related
###
weather_related
earthquake
other_aid
aid_related
related
money
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related

###
*empty element*
###
weather_related
earthquake
aid_related
related
request
money
###
weather_related
earthquake
missing_people
other_aid
aid_related
related
request
###
weather_related
earthquake
related
###
weather_related
earthquake
buildings
other_infrastructure
infrastructure_related
related
transport
###
weather_related
earthquake
aid_related
related
request
money
###
weather_related
earthquake
refugees
aid_related
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
other_infrastructure
aid_related
infrastructure_related
related
death
###
weather_related
earthquake
related
###
weather_related
earthquake
other_aid
aid_related
related
###
weather_related
earthquake
buildings
related
###
weather_related
earthquake
other_aid
aid_related
related
transport
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
other_aid
aid_related
related
###
weather_related
earthq

buildings
aid_related
related
death
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
missing_people
other_aid
aid_related
related
death
###
weather_related
earthquake
aid_related
related
search_and_rescue
###
weather_related
missing_people
aid_related
related
floods
transport
###
*empty element*
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
offer
weather_related
earthquake
aid_related
related
money
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
direct_report
medical_help
aid_related
related
request
###
weather_re

related
###
*empty element*
###
other_aid
direct_report
aid_related
related
food
###
other_aid
direct_report
clothing
aid_related
related
food
request
###
other_aid
direct_report
clothing
aid_related
related
food
money
###
weather_related
direct_report
storm
related
###
weather_related
aid_related
storm
related
food
money
###
clothing
aid_related
related
food
###
offer
clothing
aid_related
related
food
###
other_aid
clothing
aid_related
related
request
###
aid_related
related
food
###
weather_related
direct_report
storm
related
###
*empty element*
###
medical_products
aid_related
related
water
###
medical_products
aid_related
related
food
###
other_aid
direct_report
aid_related
related
###
related
###
*empty element*
###
weather_related
storm
cold
related
###
related
request
###
direct_report
related
###
related
###
clothing
aid_related
related
food
###
other_aid
clothing
aid_related
related
shelter
###
medical_products
clothing
aid_related
related
food
water
###
medical_products
aid_r

weather_related
buildings
direct_report
clothing
aid_related
related
floods
request
shelter
###
weather_related
earthquake
military
aid_related
related
transport
###
related
###
weather_related
storm
related
###
medical_products
clothing
aid_related
related
request
###
other_aid
aid_related
related
money
###
related
###
offer
clothing
aid_related
related
food
###
medical_products
other_aid
clothing
aid_related
related
food
shelter
###
weather_related
other_aid
aid_centers
aid_related
infrastructure_related
related
floods
search_and_rescue
transport
###
weather_related
medical_products
direct_report
aid_related
related
food
request
shelter
other_weather
###
related
###
weather_related
other_aid
aid_related
storm
related
food
###
weather_related
storm
related
###
related
###
*empty element*
###
direct_report
clothing
aid_related
related
food
###
clothing
aid_related
related
shelter
water
###
medical_products
clothing
aid_related
related
food
###
aid_related
related
food
request
###
relat

###
aid_related
related
food
###
weather_related
other_aid
direct_report
aid_related
related
request
electricity
other_weather
###
weather_related
direct_report
storm
related
###
weather_related
direct_report
aid_related
storm
related
food
request
###
direct_report
related
###
weather_related
earthquake
direct_report
storm
related
###
medical_products
aid_related
related
###
*empty element*
###
*empty element*
###
weather_related
direct_report
cold
related
###
medical_products
aid_related
related
food
###
aid_related
related
food
###
aid_related
related
food
shelter
###
weather_related
direct_report
storm
cold
related
request
electricity
###
related
###
related
###
direct_report
aid_related
related
food
###
weather_related
medical_products
clothing
aid_related
related
other_weather
###
related
###
related
###
other_aid
direct_report
aid_related
related
food
request
###
direct_report
aid_related
related
food
###
medical_products
direct_report
aid_related
related
request
###
weather_rela

###
*empty element*
###
*empty element*
###
other_aid
aid_related
related
###
direct_report
related
###
direct_report
related
###
related
request
###
weather_related
earthquake
direct_report
related
###
*empty element*
###
related
###
other_infrastructure
infrastructure_related
related
###
*empty element*
###
weather_related
related
other_weather
###
*empty element*
###
related
###
*empty element*
###
*empty element*
###
weather_related
related
other_weather
###
weather_related
medical_help
aid_related
related
other_weather
###
weather_related
related
other_weather
###
weather_related
related
other_weather
###
weather_related
earthquake
related
other_weather
###
weather_related
direct_report
hospitals
aid_related
storm
infrastructure_related
related
search_and_rescue
request
other_weather
###
related
###
weather_related
earthquake
related
floods
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
*empty element*
###
*empty element*
###
weather_related
eart

###
*empty element*
###
related
request
###
*empty element*
###
related
###
*empty element*
###
other_aid
direct_report
aid_related
related
request
###
related
###
weather_related
other_aid
direct_report
other_infrastructure
aid_related
infrastructure_related
related
floods
request
money
###
weather_related
other_aid
direct_report
other_infrastructure
aid_related
infrastructure_related
related
floods
request
###
*empty element*
###
related
###
other_aid
direct_report
aid_related
related
request
###
related
###
direct_report
medical_help
aid_related
related
request
###
direct_report
related
request
###
*empty element*
###
weather_related
direct_report
related
floods
###
weather_related
other_aid
buildings
direct_report
other_infrastructure
aid_related
infrastructure_related
related
food
floods
shops
request
###
weather_related
other_aid
buildings
direct_report
aid_related
related
floods
request
###
weather_related
other_aid
buildings
direct_report
other_infrastructure
aid_related
storm


###
weather_related
direct_report
aid_related
related
food
floods
request
###
other_aid
aid_related
related
food
###
*empty element*
###
weather_related
direct_report
aid_related
related
food
floods
request
shelter
###
*empty element*
###
direct_report
aid_centers
aid_related
infrastructure_related
related
food
request
###
weather_related
direct_report
other_infrastructure
medical_help
aid_related
infrastructure_related
related
floods
transport
###
related
###
weather_related
other_aid
buildings
other_infrastructure
clothing
aid_related
related
floods
shelter
transport
infrastructure_related
###
*empty element*
###
weather_related
buildings
direct_report
aid_related
related
food
floods
security
request
###
weather_related
other_aid
aid_related
related
floods
request
###
related
###
weather_related
buildings
clothing
aid_related
related
food
floods
request
###
other_aid
aid_related
related
request
###
other_aid
aid_related
related
request
###
weather_related
related
floods
###
other_aid

###
weather_related
direct_report
storm
related
electricity
###
weather_related
direct_report
storm
related
###
weather_related
storm
related
###
*empty element*
###
weather_related
storm
related
###
related
###
weather_related
storm
related
###
weather_related
storm
related
###
weather_related
direct_report
storm
related
###
weather_related
storm
related
###
weather_related
aid_related
storm
related
food
other_weather
###
related
###
*empty element*
###
weather_related
storm
related
other_weather
###
related
request
###
weather_related
direct_report
other_infrastructure
medical_help
aid_related
storm
infrastructure_related
related
###
related
###
weather_related
direct_report
storm
cold
related
###
weather_related
buildings
other_infrastructure
storm
infrastructure_related
related
###
*empty element*
###
weather_related
storm
related
###
weather_related
storm
related
electricity
###
*empty element*
###
weather_related
direct_report
storm
related
###
*empty element*
###
*empty element*

storm
related
###
weather_related
direct_report
storm
related
###
related
###
related
###
*empty element*
###
related
###
weather_related
direct_report
storm
related
electricity
###
related
###
weather_related
direct_report
medical_help
aid_related
related
floods
request
transport
###
weather_related
direct_report
aid_related
storm
related
electricity
water
###
*empty element*
###
related
###
direct_report
other_infrastructure
infrastructure_related
related
###
related
###
weather_related
other_aid
direct_report
aid_related
storm
related
electricity
###
weather_related
other_infrastructure
storm
infrastructure_related
related
transport
###
weather_related
direct_report
storm
related
###
*empty element*
###
weather_related
direct_report
storm
related
electricity
###
*empty element*
###
*empty element*
###
weather_related
direct_report
aid_related
storm
related
death
electricity
###
weather_related
direct_report
storm
related
###
weather_related
other_aid
aid_related
storm
related
reques

storm
related
###
aid_centers
aid_related
related
shelter
infrastructure_related
###
weather_related
other_infrastructure
infrastructure_related
related
floods
###
related
###
*empty element*
###
related
###
weather_related
other_infrastructure
aid_related
storm
infrastructure_related
related
floods
security
other_weather
###
weather_related
other_infrastructure
infrastructure_related
related
floods
electricity
###
related
electricity
###
*empty element*
###
aid_related
related
food
shelter
###
refugees
aid_related
related
search_and_rescue
shelter
###
aid_related
related
food
###
weather_related
aid_related
related
other_weather
water
###
*empty element*
###
related
###
*empty element*
###
military
aid_related
related
###
weather_related
storm
related
###
other_aid
aid_related
related
###
other_aid
aid_related
related
water
###
related
###
weather_related
clothing
aid_related
related
food
floods
shelter
###
*empty element*
###
military
other_aid
aid_related
related
food
###
medical_he

###
weather_related
storm
related
###
weather_related
other_aid
aid_related
related
floods
###
related
###
weather_related
storm
related
###
weather_related
storm
cold
related
###
medical_help
aid_related
related
###
weather_related
buildings
aid_related
storm
related
death
###
weather_related
aid_related
storm
related
floods
money
###
weather_related
earthquake
direct_report
other_infrastructure
infrastructure_related
related
###
weather_related
earthquake
related
###
weather_related
earthquake
direct_report
medical_help
aid_related
related
food
floods
request
shelter
transport
water
###
related
###
weather_related
earthquake
other_infrastructure
infrastructure_related
related
###
weather_related
other_aid
other_infrastructure
aid_related
storm
infrastructure_related
related
other_weather
###
weather_related
storm
related
###
weather_related
medical_products
missing_people
other_aid
direct_report
refugees
medical_help
aid_related
cold
related
floods
search_and_rescue
death
transport
#

aid_related
related
###
weather_related
aid_related
cold
related
shelter
###
weather_related
fire
related
###
weather_related
buildings
refugees
aid_related
storm
related
floods
###
weather_related
buildings
direct_report
aid_related
storm
related
death
###
weather_related
medical_products
earthquake
clothing
medical_help
aid_related
storm
related
food
floods
shelter
water
###
weather_related
storm
related
###
weather_related
earthquake
aid_related
cold
related
request
shelter
other_weather
###
weather_related
related
floods
###
weather_related
storm
related
###
weather_related
earthquake
related
###
related
###
weather_related
storm
related
###
weather_related
military
other_aid
other_infrastructure
aid_centers
refugees
aid_related
storm
infrastructure_related
related
food
transport
###
weather_related
storm
related
###
weather_related
other_aid
other_infrastructure
aid_related
storm
infrastructure_related
related
floods
###
weather_related
earthquake
aid_related
related
death
###
rel

related
floods
###
related
###
weather_related
aid_related
related
floods
death
###
other_infrastructure
aid_related
infrastructure_related
related
transport
money
###
weather_related
fire
other_aid
aid_related
related
###
weather_related
earthquake
related
other_weather
###
medical_products
other_aid
medical_help
aid_related
related
electricity
###
related
###
weather_related
direct_report
medical_help
aid_related
cold
related
floods
death
transport
###
related
###
medical_products
medical_help
aid_related
related
###
weather_related
earthquake
related
###
weather_related
earthquake
related
###
weather_related
earthquake
aid_related
related
money
###
weather_related
fire
buildings
refugees
aid_related
related
###
related
###
weather_related
medical_products
earthquake
other_aid
refugees
medical_help
aid_related
related
food
shelter
transport
water
###
weather_related
medical_help
aid_related
related
food
other_weather
water
###
weather_related
buildings
other_infrastructure
storm
infr

###
weather_related
fire
other_aid
direct_report
refugees
aid_related
related
###
weather_related
other_aid
aid_related
storm
related
other_weather
###
related
###
direct_report
related
###
*empty element*
###
weather_related
missing_people
direct_report
other_infrastructure
aid_related
infrastructure_related
cold
related
floods
request
money
###
*empty element*
###
weather_related
other_aid
aid_related
storm
related
other_weather
###
weather_related
other_infrastructure
aid_related
storm
infrastructure_related
related
death
###
weather_related
earthquake
related
###
weather_related
related
floods
###
other_aid
aid_related
related
transport
###
weather_related
earthquake
other_aid
refugees
aid_related
cold
related
###
weather_related
other_aid
aid_related
related
floods
other_weather
transport
###
*empty element*
###
other_aid
medical_help
aid_related
related
death
###
weather_related
medical_help
aid_related
cold
related
death
###
weather_related
cold
related
###
*empty element*
###
w

###
other_aid
aid_related
related
###
refugees
aid_related
related
search_and_rescue
###
weather_related
storm
related
###
related
###
weather_related
buildings
hospitals
medical_help
aid_related
infrastructure_related
related
floods
search_and_rescue
###
medical_help
aid_related
related
###
weather_related
other_aid
aid_related
related
other_weather
###
related
###
weather_related
other_aid
aid_related
storm
related
shelter
###
medical_products
other_aid
aid_related
related
food
shelter
water
###
weather_related
related
other_weather
###
weather_related
earthquake
aid_related
related
death
other_weather
###
weather_related
storm
related
other_weather
###
weather_related
related
other_weather
###
aid_related
tools
related
search_and_rescue
water
###
related
###
aid_related
related
death
###
weather_related
earthquake
aid_related
storm
cold
related
death
other_weather
###
weather_related
military
other_infrastructure
aid_related
infrastructure_related
related
floods
search_and_rescue
de

###
weather_related
cold
related
###
weather_related
refugees
aid_related
related
floods
###
weather_related
earthquake
related
###
related
###
related
###
weather_related
cold
related
###
other_aid
aid_related
related
###
weather_related
medical_help
aid_related
cold
related
request
electricity
###
weather_related
related
floods
###
buildings
medical_help
aid_related
related
###
weather_related
other_aid
aid_related
storm
related
floods
money
###
weather_related
storm
related
floods
###
weather_related
storm
related
floods
###
weather_related
storm
related
###
related
###
buildings
aid_related
related
death
###
related
###
weather_related
earthquake
aid_related
related
money
###
weather_related
missing_people
other_aid
medical_help
aid_related
related
floods
other_weather
transport
###
weather_related
other_aid
aid_related
storm
related
floods
death
other_weather
###
weather_related
earthquake
buildings
refugees
aid_related
infrastructure_related
related
shops
###
weather_related
aid_

medical_help
aid_related
related
###
weather_related
storm
related
###
weather_related
related
floods
###
weather_related
other_infrastructure
storm
infrastructure_related
related
floods
transport
###
related
###
*empty element*
###
weather_related
storm
related
###
weather_related
storm
related
###
*empty element*
###
related
###
other_aid
other_infrastructure
medical_help
aid_related
infrastructure_related
related
food
###
related
###
*empty element*
###
related
###
weather_related
aid_related
storm
related
security
###
weather_related
medical_products
fire
direct_report
aid_related
related
electricity
###
*empty element*
###
weather_related
other_aid
aid_related
related
floods
###
weather_related
aid_related
related
food
floods
###
weather_related
cold
related
other_weather
###
weather_related
buildings
storm
related
floods
###
related
###
other_infrastructure
infrastructure_related
related
###
weather_related
fire
other_aid
aid_centers
medical_help
aid_related
infrastructure_relate

###
weather_related
storm
related
###
weather_related
buildings
aid_related
storm
related
shelter
###
weather_related
missing_people
aid_related
related
death
other_weather
###
weather_related
storm
cold
related
###
weather_related
buildings
related
floods
###
weather_related
storm
related
floods
###
other_infrastructure
aid_related
infrastructure_related
related
food
money
###
weather_related
buildings
refugees
aid_related
storm
related
shelter
###
*empty element*
###
related
###
related
###
related
###
weather_related
aid_related
related
death
other_weather
###
weather_related
other_aid
aid_related
storm
related
search_and_rescue
###
weather_related
storm
related
###
*empty element*
###
weather_related
medical_products
earthquake
aid_related
related
food
shelter
###
related
###
weather_related
storm
related
floods
other_weather
transport
###
related
###
weather_related
earthquake
related
###
weather_related
earthquake
missing_people
buildings
refugees
aid_related
related
death
###
ot

related
request
###
weather_related
fire
related
###
weather_related
fire
earthquake
aid_related
storm
related
death
other_weather
###
weather_related
direct_report
storm
related
floods
###
weather_related
storm
related
###
weather_related
storm
related
floods
###
weather_related
medical_products
aid_related
cold
related
request
###
*empty element*
###
*empty element*
###
weather_related
medical_products
missing_people
other_aid
other_infrastructure
clothing
refugees
aid_related
infrastructure_related
related
floods
security
other_weather
transport
###
weather_related
related
other_weather
###
related
###
weather_related
earthquake
related
###
weather_related
related
other_weather
###
*empty element*
###
related
###
*empty element*
###
weather_related
aid_centers
aid_related
related
floods
shelter
infrastructure_related
money
###
related
###
other_infrastructure
aid_related
infrastructure_related
related
death
###
related
###
medical_products
hospitals
medical_help
aid_related
infrastr

weather_related
other_infrastructure
storm
infrastructure_related
related
other_weather
###
weather_related
other_infrastructure
storm
infrastructure_related
related
###
medical_help
aid_related
related
###
other_aid
aid_related
related
electricity
water
###
*empty element*
###
weather_related
refugees
aid_related
related
floods
shelter
###
weather_related
other_aid
aid_related
storm
related
death
###
weather_related
other_infrastructure
infrastructure_related
related
floods
###
weather_related
aid_related
related
other_weather
water
###
related
###
*empty element*
###
weather_related
related
other_weather
###
weather_related
earthquake
other_aid
aid_related
related
food
other_weather
###
weather_related
other_aid
other_infrastructure
aid_related
storm
infrastructure_related
related
###
weather_related
cold
related
###
weather_related
aid_related
storm
related
other_weather
water
###
direct_report
related
###
weather_related
fire
earthquake
other_aid
medical_help
aid_related
storm
cold

offer
hospitals
medical_help
aid_related
infrastructure_related
related
search_and_rescue
###
weather_related
earthquake
direct_report
aid_related
related
shelter
###
weather_related
medical_products
medical_help
aid_related
related
food
floods
###
medical_help
aid_related
related
death
###
related
###
other_aid
aid_related
related
###
weather_related
medical_products
medical_help
aid_related
related
floods
###
other_aid
direct_report
aid_related
related
###
related
###
aid_related
related
death
###
weather_related
related
other_weather
###
related
###
clothing
aid_related
related
food
water
###
weather_related
earthquake
aid_related
tools
cold
related
floods
security
death
###
medical_products
other_aid
aid_related
related
###
weather_related
earthquake
missing_people
buildings
aid_related
related
search_and_rescue
###
weather_related
direct_report
related
other_weather
###
related
###
*empty element*
###
weather_related
earthquake
buildings
hospitals
aid_related
related
shelter
other

*empty element*
###
weather_related
storm
related
###
weather_related
fire
related
other_weather
###
related
###
weather_related
storm
related
###
medical_help
aid_related
related
###
medical_help
aid_related
related
###
weather_related
earthquake
related
###
weather_related
medical_help
aid_related
storm
related
floods
death
transport
###
refugees
aid_related
related
security
###
weather_related
military
aid_related
related
food
other_weather
###
weather_related
storm
related
floods
###
weather_related
buildings
aid_related
storm
related
death
other_weather
###
related
###
*empty element*
###
related
###
weather_related
aid_related
related
floods
money
###
weather_related
medical_products
missing_people
other_aid
medical_help
aid_related
related
floods
security
transport
###
related
###
weather_related
storm
related
###
weather_related
medical_products
refugees
aid_related
related
floods
security
shelter
transport
###
other_aid
other_infrastructure
aid_centers
aid_related
related
shel

related
other_weather
###
weather_related
storm
related
###
aid_related
related
death
###
medical_products
aid_centers
medical_help
aid_related
related
shelter
infrastructure_related
###
weather_related
fire
buildings
related
###
other_aid
aid_related
related
shelter
###
aid_related
related
security
###
related
###
weather_related
earthquake
related
###
direct_report
related
###
related
###
*empty element*
###
related
###
weather_related
storm
related
floods
###
weather_related
other_aid
refugees
medical_help
aid_related
storm
related
floods
###
other_aid
aid_related
related
###
weather_related
missing_people
aid_related
storm
related
death
###
aid_related
related
water
###
*empty element*
###
related
###
related
###
weather_related
missing_people
aid_related
storm
related
search_and_rescue
death
###
aid_related
related
money
###
related
###
weather_related
other_infrastructure
storm
infrastructure_related
related
floods
###
weather_related
medical_products
other_infrastructure
refugee

related
###
offer
aid_related
related
money
###
related
###
other_aid
aid_related
related
search_and_rescue
###
weather_related
medical_products
medical_help
aid_related
storm
related
###
weather_related
storm
cold
related
###
direct_report
related
###
*empty element*
###
related
###
related
###
other_aid
aid_related
related
###
weather_related
earthquake
other_aid
aid_related
related
search_and_rescue
shelter
other_weather
###
weather_related
related
floods
###
*empty element*
###
aid_related
related
death
###
weather_related
related
other_weather
###
aid_related
related
food
###
weather_related
earthquake
other_aid
aid_related
storm
related
###
weather_related
fire
related
###
weather_related
other_aid
aid_related
related
other_weather
###
*empty element*
###
*empty element*
###
weather_related
other_aid
aid_related
related
other_weather
###
weather_related
earthquake
medical_help
aid_related
related
###
weather_related
fire
buildings
related
other_weather
###
military
aid_related
re

weather_related
storm
related
###
related
###
related
###
weather_related
aid_related
related
floods
money
###
related
###
*empty element*
###
related
###
related
###
related
###
*empty element*
###
weather_related
medical_products
other_infrastructure
clothing
refugees
aid_related
storm
infrastructure_related
related
money
###
military
aid_related
related
###
*empty element*
###
weather_related
medical_help
aid_related
related
floods
money
###
buildings
direct_report
aid_related
related
search_and_rescue
###
related
###
offer
weather_related
medical_products
direct_report
medical_help
aid_related
related
food
floods
transport
###
weather_related
storm
related
###
related
###
weather_related
medical_products
earthquake
missing_people
buildings
other_infrastructure
clothing
aid_centers
refugees
medical_help
aid_related
storm
related
food
floods
search_and_rescue
shelter
other_weather
transport
water
infrastructure_related
###
related
###
*empty element*
###
weather_related
aid_related
r

*empty element*
###
weather_related
medical_help
aid_related
related
floods
transport
###
buildings
related
###
weather_related
military
aid_related
related
floods
###
*empty element*
###
weather_related
related
other_weather
###
weather_related
medical_products
other_aid
aid_centers
aid_related
infrastructure_related
related
floods
###
weather_related
medical_help
aid_related
storm
related
floods
transport
###
weather_related
refugees
aid_related
storm
related
###
*empty element*
###
*empty element*
###
related
###
related
transport
###
*empty element*
###
related
###
related
###
related
###
*empty element*
###
medical_help
aid_related
related
###
related
###
related
###
*empty element*
###
weather_related
other_aid
buildings
aid_related
storm
related
shelter
###
related
###
related
###
weather_related
storm
related
floods
###
related
###
direct_report
related
transport
###
buildings
related
###
*empty element*
###
weather_related
other_infrastructure
refugees
aid_related
related
shop

###
weather_related
other_infrastructure
infrastructure_related
related
floods
###
*empty element*
###
weather_related
storm
related
###
related
###
*empty element*
###
weather_related
earthquake
related
floods
###
related
###
weather_related
medical_products
hospitals
medical_help
aid_related
infrastructure_related
related
other_weather
###
related
###
related
###
*empty element*
###
weather_related
related
other_weather
###
medical_help
aid_related
related
death
###
related
###
weather_related
fire
other_aid
aid_related
related
###
related
###
weather_related
medical_products
hospitals
aid_related
infrastructure_related
cold
related
###
weather_related
direct_report
related
other_weather
###
related
###
weather_related
earthquake
buildings
aid_related
related
shelter
###
weather_related
storm
related
###
medical_products
other_aid
medical_help
aid_related
related
food
request
water
###
weather_related
related
other_weather
###
related
###
other_aid
aid_related
related
###
related
###

related
###
military
aid_related
related
###
related
###
weather_related
earthquake
buildings
related
###
medical_help
aid_related
related
water
###
weather_related
related
floods
###
weather_related
direct_report
storm
related
request
###
*empty element*
###
*empty element*
###
*empty element*
###
aid_related
related
search_and_rescue
###
other_infrastructure
aid_related
infrastructure_related
related
water
###
military
aid_related
related
###
weather_related
other_aid
medical_help
aid_related
related
floods
transport
###
*empty element*
###
weather_related
earthquake
buildings
related
transport
###
related
###
other_aid
aid_related
related
shelter
water
###
*empty element*
###
*empty element*
###
related
###
refugees
aid_related
related
food
###
related
###
missing_people
other_aid
direct_report
aid_related
related
search_and_rescue
###
related
###
related
###
military
aid_related
related
###
*empty element*
###
related
electricity
###
related
###
military
aid_related
related
food
se

###
related
###
military
aid_related
related
###
related
###
medical_products
aid_related
related
request
###
related
###
military
aid_related
related
security
###
medical_help
aid_related
related
###
aid_related
related
shelter
###
medical_help
aid_related
related
###
weather_related
medical_help
aid_related
storm
related
request
electricity
###
military
aid_related
related
security
###
related
###
weather_related
earthquake
aid_related
storm
related
money
###
related
###
aid_related
related
food
death
###
*empty element*
###
related
###
weather_related
buildings
refugees
aid_related
related
floods
request
shelter
###
*empty element*
###
*empty element*
###
related
###
related
###
*empty element*
###
other_infrastructure
hospitals
medical_help
aid_related
infrastructure_related
related
search_and_rescue
electricity
transport
###
*empty element*
###
weather_related
military
medical_help
aid_related
related
floods
security
transport
###
*empty element*
###
*empty element*
###
hospitals


###
*empty element*
###
related
###
weather_related
direct_report
medical_help
aid_related
related
floods
request
transport
###
*empty element*
###
related
###
weather_related
medical_products
buildings
other_infrastructure
aid_centers
aid_related
infrastructure_related
related
floods
water
###
*empty element*
###
weather_related
medical_help
aid_related
storm
related
other_weather
transport
###
related
###
weather_related
buildings
related
floods
transport
###
weather_related
related
floods
###
weather_related
medical_products
other_aid
refugees
aid_related
related
food
floods
shelter
electricity
water
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
medical_products
buildings
other_infrastructure
hospitals
medical_help
aid_related
related
food
shelter
infrastructure_related
###
related
###
refugees
aid_related
related
###
related
###
refugees
aid_related
related
###
weather_related
other_aid
medical_help
aid_related
related
other_weather
###
medical_product

aid_related
tools
related
floods
search_and_rescue
security
request
other_weather
transport
water
###
related
###
aid_related
related
water
###
related
###
related
###
buildings
other_infrastructure
refugees
aid_related
related
shelter
infrastructure_related
###
related
###
*empty element*
###
aid_related
related
request
water
###
weather_related
medical_products
other_aid
aid_related
related
other_weather
###
military
refugees
aid_related
related
death
###
medical_products
direct_report
medical_help
aid_related
related
request
###
weather_related
medical_products
fire
military
medical_help
aid_related
storm
related
food
floods
search_and_rescue
shelter
death
electricity
###
related
###
*empty element*
###
weather_related
aid_related
related
floods
shelter
###
*empty element*
###
medical_products
medical_help
aid_related
related
###
aid_related
related
food
shelter
water
###
aid_related
related
money
###
weather_related
medical_products
clothing
medical_help
aid_related
related
food
ot

related
transport
###
aid_related
related
death
###
*empty element*
###
*empty element*
###
related
###
related
###
related
###
aid_related
tools
related
shelter
money
###
weather_related
related
floods
other_weather
###
medical_help
aid_related
related
###
direct_report
related
request
###
military
other_aid
aid_related
related
###
related
###
related
###
*empty element*
###
*empty element*
###
*empty element*
###
missing_people
aid_related
related
###
weather_related
medical_products
earthquake
medical_help
aid_related
infrastructure_related
related
shops
transport
###
weather_related
other_aid
other_infrastructure
aid_related
infrastructure_related
related
floods
electricity
transport
###
direct_report
aid_related
related
water
###
medical_help
aid_related
related
###
medical_help
aid_related
related
###
weather_related
buildings
other_infrastructure
storm
infrastructure_related
related
###
related
electricity
###
*empty element*
###
weather_related
buildings
direct_report
medical_h

aid_related
related
death
###
other_aid
aid_related
related
###
aid_related
related
water
###
*empty element*
###
related
###
related
###
*empty element*
###
related
###
related
###
related
###
*empty element*
###
weather_related
other_aid
medical_help
aid_related
related
food
floods
other_weather
transport
###
related
###
related
###
medical_help
aid_related
related
###
related
###
*empty element*
###
other_infrastructure
infrastructure_related
related
###
other_aid
direct_report
aid_related
related
food
request
###
related
###
related
###
weather_related
storm
related
floods
electricity
###
aid_related
related
shelter
###
other_infrastructure
infrastructure_related
related
electricity
###
*empty element*
###
aid_related
related
search_and_rescue
###
*empty element*
###
related
###
weather_related
earthquake
hospitals
aid_related
infrastructure_related
related
death
###
weather_related
fire
related
###
*empty element*
###
military
aid_related
related
###
weather_related
other_aid
aid_

###
weather_related
buildings
storm
related
###
*empty element*
###
aid_related
related
food
###
*empty element*
###
*empty element*
###
*empty element*
###
weather_related
other_aid
direct_report
aid_related
related
food
shelter
other_weather
###
*empty element*
###
other_aid
direct_report
aid_related
related
###
aid_related
related
water
###
related
###
weather_related
other_infrastructure
infrastructure_related
related
floods
electricity
###
related
###
military
aid_related
related
###
*empty element*
###
related
###
*empty element*
###
*empty element*
###
other_infrastructure
aid_centers
hospitals
infrastructure_related
related
###
medical_help
aid_related
related
###
related
###
weather_related
medical_products
medical_help
aid_related
tools
cold
related
transport
###
related
###
medical_products
clothing
aid_related
related
food
shelter
###
related
###
weather_related
medical_products
buildings
medical_help
aid_related
storm
related
death
electricity
water
###
other_aid
aid_relat

###
related
###
related
###
direct_report
related
request
###
medical_products
aid_related
related
food
###
*empty element*
###
related
###
related
###
related
###
weather_related
refugees
aid_related
related
other_weather
###
weather_related
related
other_weather
###
*empty element*
###
related
###
military
aid_related
related
food
security
###
*empty element*
###
aid_related
related
food
water
###
other_aid
aid_related
related
###
*empty element*
###
aid_related
related
water
###
related
###
*empty element*
###
related
###
buildings
related
###
medical_help
aid_related
related
###
aid_related
related
shelter
###
other_aid
direct_report
aid_related
related
###
weather_related
aid_related
related
floods
money
###
related
###
weather_related
aid_related
cold
related
shelter
###
medical_products
aid_related
related
food
shelter
water
###
direct_report
related
request
###
*empty element*
###
related
###
*empty element*
###
*empty element*
###
medical_products
other_aid
aid_related
related

floods
shelter
infrastructure_related
###
related
###
weather_related
earthquake
other_aid
buildings
other_infrastructure
aid_related
infrastructure_related
related
transport
###
medical_help
aid_related
related
###
related
###
related
###
other_aid
aid_related
related
###
weather_related
fire
aid_centers
aid_related
infrastructure_related
related
food
search_and_rescue
###
related
###
weather_related
other_aid
aid_related
storm
related
###
weather_related
other_infrastructure
infrastructure_related
related
other_weather
###
direct_report
related
electricity
###
*empty element*
###
related
###
*empty element*
###
weather_related
hospitals
aid_related
storm
infrastructure_related
related
death
###
related
###
related
###
aid_related
related
search_and_rescue
transport
###
*empty element*
###
*empty element*
###
*empty element*
###
aid_related
related
death
###
other_aid
aid_related
related
###
related
###
infrastructure_related
related
shops
###
aid_related
related
water
###
other_aid
a

aid_related
related
###
*empty element*
###
weather_related
other_infrastructure
infrastructure_related
related
other_weather
###
aid_related
related
food
###
other_aid
aid_related
related
###
other_aid
buildings
aid_related
related
###
buildings
related
###
*empty element*
###
*empty element*
###
aid_related
related
money
###
*empty element*
###
weather_related
fire
direct_report
aid_related
related
search_and_rescue
electricity
###
other_aid
aid_related
related
###
related
###
weather_related
storm
related
###
related
###
*empty element*
###
direct_report
related
###
weather_related
buildings
aid_centers
hospitals
aid_related
related
floods
shelter
electricity
transport
infrastructure_related
###
*empty element*
###
*empty element*
###
direct_report
aid_related
related
water
###
weather_related
medical_help
aid_related
related
floods
###
other_infrastructure
infrastructure_related
related
###
aid_related
related
shelter
###
military
refugees
aid_related
related
###
weather_related
fi

###
*empty element*
###
military
aid_related
related
water
###
other_aid
aid_related
related
money
###
*empty element*
###
weather_related
storm
related
floods
transport
###
weather_related
refugees
aid_related
related
other_weather
###
weather_related
medical_products
earthquake
clothing
aid_related
related
shelter
###
medical_help
aid_related
related
food
money
###
other_aid
aid_related
related
###
related
###
*empty element*
###
related
###
weather_related
medical_products
direct_report
aid_centers
aid_related
storm
infrastructure_related
related
security
request
other_weather
###
weather_related
other_aid
medical_help
aid_related
related
food
floods
search_and_rescue
shelter
###
*empty element*
###
other_aid
aid_related
related
###
*empty element*
###
related
###
aid_related
related
water
###
*empty element*
###
weather_related
buildings
other_infrastructure
infrastructure_related
related
floods
###
medical_help
aid_related
related
###
direct_report
related
transport
###
weather_re

###
*empty element*
###
aid_related
related
food
###
weather_related
other_aid
direct_report
other_infrastructure
aid_related
infrastructure_related
related
other_weather
###
hospitals
medical_help
aid_related
infrastructure_related
related
###
related
###
*empty element*
###
weather_related
buildings
other_infrastructure
infrastructure_related
related
floods
transport
###
related
###
weather_related
military
medical_help
aid_related
related
other_weather
###
*empty element*
###
*empty element*
###
weather_related
medical_help
aid_related
related
floods
request
shelter
transport
###
related
###
related
###
weather_related
aid_related
related
food
other_weather
###
*empty element*
###
weather_related
other_aid
other_infrastructure
aid_related
infrastructure_related
tools
related
floods
###
direct_report
infrastructure_related
related
shops
request
###
medical_products
clothing
aid_related
related
food
shelter
water
###
medical_products
aid_related
related
food
money
###
weather_related


aid_related
related
food
###
offer
medical_products
aid_related
related
###
*empty element*
###
weather_related
refugees
medical_help
aid_related
storm
related
###
*empty element*
###
related
###
*empty element*
###
weather_related
fire
related
###
related
###
*empty element*
###
aid_related
related
search_and_rescue
transport
###
weather_related
fire
military
buildings
aid_related
related
death
###
related
###
weather_related
earthquake
other_aid
buildings
other_infrastructure
aid_related
related
security
shelter
infrastructure_related
money
###
related
###
refugees
aid_related
related
food
shelter
###
*empty element*
###
aid_related
related
food
###
aid_centers
aid_related
related
shelter
infrastructure_related
###
*empty element*
###
medical_products
other_infrastructure
aid_related
infrastructure_related
related
###
missing_people
other_infrastructure
aid_related
infrastructure_related
related
###
weather_related
medical_products
other_infrastructure
medical_help
aid_related
relate

###
medical_products
other_aid
aid_related
related
food
shelter
water
###
*empty element*
###
direct_report
aid_related
related
shelter
###
weather_related
medical_products
earthquake
other_aid
aid_related
related
food
request
water
###
*empty element*
###
related
transport
###
weather_related
medical_products
buildings
aid_related
related
floods
shelter
###
aid_centers
refugees
aid_related
related
shelter
infrastructure_related
###
weather_related
aid_related
related
food
floods
###
other_aid
aid_related
related
water
###
related
###
weather_related
other_aid
aid_related
related
food
other_weather
###
weather_related
earthquake
aid_related
related
food
###
other_aid
aid_related
related
###
related
###
aid_related
related
food
water
###
weather_related
medical_help
aid_related
storm
related
floods
transport
###
weather_related
direct_report
aid_related
cold
related
floods
electricity
water
###
aid_related
related
water
###
weather_related
related
other_weather
###
related
###
*empty el

weather_related
related
floods
###
aid_related
related
death
###
weather_related
military
other_infrastructure
aid_related
infrastructure_related
related
floods
death
###
medical_products
other_aid
direct_report
medical_help
aid_related
related
###
related
electricity
###
*empty element*
###
medical_help
aid_related
related
money
###
*empty element*
###
weather_related
related
floods
###
related
###
weather_related
earthquake
related
###
other_aid
aid_related
related
transport
###
buildings
other_infrastructure
infrastructure_related
related
###
military
aid_related
related
###
related
###
weather_related
military
medical_help
aid_related
related
floods
death
transport
###
*empty element*
###
related
###
weather_related
other_aid
other_infrastructure
aid_related
storm
related
food
floods
shelter
infrastructure_related
###
related
###
medical_help
aid_related
related
###
related
###
weather_related
refugees
medical_help
aid_related
related
floods
transport
###
*empty element*
###
weathe

###
*empty element*
###
related
###
refugees
aid_related
related
###
*empty element*
###
other_aid
aid_related
related
###
related
###
weather_related
other_aid
aid_related
tools
related
floods
###
other_aid
refugees
aid_related
related
shelter
###
buildings
aid_related
related
death
###
weather_related
other_aid
aid_related
cold
related
###
weather_related
earthquake
medical_help
aid_related
related
###
other_aid
aid_related
related
shelter
###
medical_help
aid_related
related
###
other_aid
aid_related
related
food
###
other_infrastructure
infrastructure_related
related
transport
###
military
aid_related
related
###
related
###
other_aid
aid_related
related
shelter
water
money
###
related
###
related
###
related
electricity
###
weather_related
earthquake
related
###
weather_related
earthquake
aid_related
related
request
money
###
direct_report
related
request
###
related
electricity
###
related
###
other_aid
aid_related
related
search_and_rescue
###
related
###
related
###
medical_pro

###
weather_related
medical_products
medical_help
aid_related
related
floods
###
medical_help
aid_related
related
###
weather_related
earthquake
other_infrastructure
infrastructure_related
related
###
other_aid
aid_related
related
food
transport
###
other_aid
aid_related
related
###
*empty element*
###
medical_products
medical_help
aid_related
related
request
###
medical_products
direct_report
refugees
aid_related
related
food
water
###
related
###
aid_related
related
food
###
related
###
related
###
other_aid
aid_related
related
food
water
###
weather_related
related
other_weather
###
*empty element*
###
related
###
aid_related
related
money
###
other_aid
aid_related
related
###
*empty element*
###
military
aid_related
related
death
###
clothing
medical_help
aid_related
related
food
security
money
###
aid_related
related
death
###
related
###
*empty element*
###
related
###
other_aid
aid_related
related
money
###
weather_related
other_aid
aid_centers
medical_help
aid_related
infrastru

###
related
###
other_aid
aid_related
related
water
###
missing_people
military
aid_related
related
food
search_and_rescue
###
*empty element*
###
weather_related
direct_report
medical_help
aid_related
related
floods
request
transport
###
*empty element*
###
weather_related
other_aid
aid_related
related
other_weather
###
military
aid_related
related
###
*empty element*
###
weather_related
missing_people
aid_related
related
floods
death
###
other_aid
medical_help
aid_related
related
food
###
weather_related
earthquake
other_aid
aid_related
related
death
###
weather_related
earthquake
clothing
aid_related
related
shelter
###
weather_related
related
floods
###
*empty element*
###
*empty element*
###
weather_related
refugees
aid_related
related
floods
###
*empty element*
###
*empty element*
###
direct_report
related
request
###
other_aid
aid_related
related
###
military
aid_related
related
###
medical_help
aid_related
related
###
medical_help
aid_related
related
death
###
refugees
aid_rela

###
aid_related
related
water
###
medical_products
other_aid
clothing
aid_related
related
shelter
water
###
*empty element*
###
weather_related
other_aid
aid_related
related
food
shelter
other_weather
transport
###
weather_related
direct_report
medical_help
aid_related
related
floods
request
###
direct_report
medical_help
aid_related
related
###
aid_related
related
food
request
water
###
other_aid
buildings
aid_related
tools
related
shelter
death
###
*empty element*
###
medical_help
aid_related
related
food
###
related
transport
###
medical_help
aid_related
related
###
medical_products
other_aid
aid_centers
refugees
medical_help
aid_related
related
shelter
infrastructure_related
###
other_aid
aid_related
related
shelter
###
aid_related
related
money
###
*empty element*
###
related
###
related
###
*empty element*
###
aid_related
related
death
###
*empty element*
###
direct_report
other_infrastructure
infrastructure_related
related
###
buildings
related
###
*empty element*
###
related
##

earthquake
other_aid
aid_related
related
###
related
###
military
aid_related
related
###
medical_products
medical_help
aid_related
related
food
shelter
###
military
aid_related
related
search_and_rescue
###
military
aid_related
related
###
weather_related
other_infrastructure
infrastructure_related
related
floods
###
related
###
weather_related
earthquake
aid_related
tools
related
search_and_rescue
###
buildings
aid_related
related
death
###
military
aid_related
related
security
death
###
weather_related
earthquake
direct_report
aid_related
related
search_and_rescue
electricity
###
*empty element*
###
weather_related
storm
related
electricity
###
weather_related
direct_report
medical_help
aid_related
related
food
floods
request
transport
###
weather_related
medical_products
earthquake
medical_help
aid_related
related
food
shelter
death
water
###
military
aid_related
related
###
related
###
medical_help
aid_related
related
food
request
###
aid_related
related
security
###
medical_produ

related
food
###
*empty element*
###
military
aid_related
related
###
aid_related
related
search_and_rescue
transport
###
related
###
related
###
weather_related
earthquake
related
###
related
###
medical_products
medical_help
aid_related
related
###
medical_products
hospitals
medical_help
aid_related
infrastructure_related
related
###
related
###
*empty element*
###
weather_related
medical_products
other_aid
buildings
other_infrastructure
aid_centers
refugees
hospitals
medical_help
aid_related
related
food
floods
shelter
death
electricity
other_weather
transport
water
infrastructure_related
###
military
aid_related
related
###
related
###
weather_related
other_aid
aid_related
related
shelter
other_weather
###
*empty element*
###
related
###
aid_related
related
death
###
weather_related
aid_related
storm
related
food
electricity
water
###
medical_products
clothing
aid_related
related
food
shelter
###
*empty element*
###
*empty element*
###
*empty element*
###
related
###
medical_produc

missing_people
military
aid_related
related
search_and_rescue
###
aid_related
related
shelter
###
military
direct_report
aid_related
related
security
request
###
related
###
military
aid_related
related
security
###
related
###
medical_products
direct_report
medical_help
aid_related
related
###
aid_related
related
food
###
weather_related
aid_related
storm
related
shelter
###
weather_related
aid_related
related
food
other_weather
###
related
###
other_aid
aid_related
related
food
money
###
weather_related
other_aid
aid_related
related
floods
electricity
transport
###
other_aid
aid_related
related
money
###
direct_report
related
###
*empty element*
###
aid_related
related
security
###
offer
weather_related
other_aid
medical_help
aid_related
related
floods
water
###
related
###
*empty element*
###
medical_products
other_aid
aid_related
related
food
request
water
###
direct_report
related
transport
###
aid_related
related
search_and_rescue
###
related
###
*empty element*
###
military
aid_

aid_related
related
food
###
hospitals
medical_help
aid_related
infrastructure_related
related
###
weather_related
military
buildings
medical_help
aid_related
cold
related
###
related
###
related
###
*empty element*
###
*empty element*
###
related
###
related
###
medical_help
aid_related
related
water
###
military
aid_related
related
###
weather_related
earthquake
buildings
related
###
related
###
medical_products
medical_help
aid_related
related
###
missing_people
military
aid_related
related
###
military
aid_related
related
###
offer
medical_products
other_aid
aid_related
related
###
related
###
weather_related
earthquake
aid_related
related
money
###
*empty element*
###
*empty element*
###
weather_related
buildings
aid_related
related
floods
death
money
###
related
###
weather_related
storm
related
###
weather_related
medical_products
earthquake
military
other_aid
buildings
other_infrastructure
aid_centers
refugees
medical_help
aid_related
infrastructure_related
related
death
transp

###
related
###
related
###
related
###
weather_related
aid_centers
hospitals
aid_related
infrastructure_related
related
floods
death
###
weather_related
storm
related
transport
###
military
aid_related
related
death
###
*empty element*
###
*empty element*
###
*empty element*
###
weather_related
related
floods
###
aid_related
related
food
###
weather_related
refugees
aid_related
related
floods
shelter
###
aid_related
related
death
###
related
###
related
###
military
aid_related
related
security
death
###
*empty element*
###
related
###
*empty element*
###
related
###
related
###
related
###
*empty element*
###
military
aid_related
related
###
*empty element*
###
related
###
weather_related
medical_products
missing_people
other_aid
medical_help
aid_related
related
floods
request
transport
###
related
###
related
###
other_aid
medical_help
aid_related
related
###
*empty element*
###
*empty element*
###
related
###
related
###
related
###
related
###
weather_related
medical_products
othe

### 5. Replace `categories` column in `df` with new category columns.
- Drop the categories column from the df dataframe since it is no longer needed.
- Concatenate df and categories data frames.

In [14]:
df = df.drop('categories', axis=1)
df.head(1)

message  \
id                                                      
2   Weather update - a cold front from Cuba that c...   

                                             original   genre  if_blank  \
id                                                                        
2   Un front froid se retrouve sur Cuba ce matin. ...  direct     False   

    related  request  offer  aid_related  medical_help  medical_products  ...  \
id                                                                        ...   
2         1        0      0            0             0                 0  ...   

    aid_centers  other_infrastructure  weather_related  floods  storm  fire  \
id                                                                            
2             0                     0                0       0      0     0   

    earthquake  cold  other_weather  direct_report  
id                                                  
2            0     0              0              0  

[1 rows x 40 columns]

### 7. Save the clean dataset into an sqlite database.
You can do this with pandas [`to_sql` method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html) combined with the SQLAlchemy library. Remember to import SQLAlchemy's `create_engine` in the first cell of this notebook to use it below.

drop table function [here](import logging
from sqlalchemy import MetaData
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL
from sqlalchemy.ext.declarative import declarative_base)

Better way to do this, [here](https://stackoverflow.com/questions/8645250/how-to-close-sqlalchemy-connection-in-mysql)

- according to the answerer, "Engine is a **factory** for connections as well as a pool of connections, not the connection itself";
- so, to avoid the problem of couldn´t closse the connection, as other members of the poll remaining asking for transactions, the answerer recommends to use **poolclass=NulPool**;
- as we are not dealing with something that really needs a pool (only one transaction per time for us is enough), let´s do it!

In [15]:
database = create_engine('sqlite:///Messages.db', poolclass=NullPool) #, echo=True)
connection = database.connect()

#attempt to save my dataframe to SQLite
try:
    df.to_sql('Messages', database, index=False, if_exists='replace')
except ValueError:
    print('something went wrong when was writing data do SQLite')
    
connection.close()

In [16]:
spent = time() - gen_begin
print('total elapsed time: {:.1f}s ({}min, {:.4f}sec)'.format(spent, math.trunc((spent)/60), math.fmod(spent, 60)))
df.head()

total elapsed time: 37.5s (0min, 37.4843sec)


message  \
id                                                      
2   Weather update - a cold front from Cuba that c...   
7             Is the Hurricane over or is it not over   
8                     Looking for someone but no name   
9   UN reports Leogane 80-90 destroyed. Only Hospi...   
12  says: west side of Haiti, rest of the country ...   

                                             original   genre  if_blank  \
id                                                                        
2   Un front froid se retrouve sur Cuba ce matin. ...  direct     False   
7                  Cyclone nan fini osinon li pa fini  direct     False   
8   Patnm, di Maryani relem pou li banm nouvel li ...  direct     False   
9   UN reports Leogane 80-90 destroyed. Only Hospi...  direct     False   
12  facade ouest d Haiti et le reste du pays aujou...  direct     False   

    related  request  offer  aid_related  medical_help  medical_products  ...  \
id                                                                        ...   
2         1        0      0            0             0                 0  ...   
7         1        0      0            1             0                 0  ...   
8         1        0      0            0             0                 0  ...   
9         1        1      0            1             0                 1  ...   
12        1        0      0            0             0                 0  ...   

    aid_centers  other_infrastructure  weather_related  floods  storm  fire  \
id                                                                            
2             0                     0                0       0      0     0   
7             0                     0                1       0      1     0   
8             0                     0                0       0      0     0   
9             0                     0                0       0      0     0   
12            0                     0                0       0      0     0   

    earthquake  cold  other_weather  direct_report  
id                                                  
2            0     0              0              0  
7            0     0              0              0  
8            0     0              0              0  
9            0     0              0              0  
12           0     0              0              0  

[5 rows x 40 columns]

In [17]:
df.columns

Index(['message', 'original', 'genre', 'if_blank', 'related', 'request',
       'offer', 'aid_related', 'medical_help', 'medical_products',
       'search_and_rescue', 'security', 'military', 'child_alone', 'water',
       'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees',
       'death', 'other_aid', 'infrastructure_related', 'transport',
       'buildings', 'electricity', 'tools', 'hospitals', 'shops',
       'aid_centers', 'other_infrastructure', 'weather_related', 'floods',
       'storm', 'fire', 'earthquake', 'cold', 'other_weather',
       'direct_report'],
      dtype='object')

### 8. Use this notebook to complete `etl_pipeline.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database based on new datasets specified by the user. Alternatively, you can complete `etl_pipeline.py` in the classroom on the `Project Workspace IDE` coming later.

*this was made into a new notebook named `ETL Pipeline Test.py`, and at `etl_pipeline.py`*

---

## Later tests over the generated dataset

Count the valid registers for one column, according to a **criteria**:

- `fn_count_valids` created

In [18]:
df.shape[0]

26245

A test for the function for counting the valid labels for one column

In [19]:
total = df.shape[0]
field = 'if_blank'
count = udacourse2.fn_count_valids(dataset=df, field=field, criteria=True)
percent = 100. * (count / total)
print('{}:{} ({:.1f}%)'.format(field, count, percent))

if_blank:6317 (24.1%)


Turning this into a function

- `fn_valids_report` created

In [20]:
udacourse2.fn_valids_report(dataset=df)

###function valids_report started
  *if_blank:6317 (24.1%)


---

Labels columns, by **hierarchical structure**

*See discussion above*

In [21]:
expand_lst = ['related', 'request', 'offer', 'aid_related', 'infrastructure_related', 'weather_related', 
              'direct_report']

aid_lst = ['food', 'shelter', 'water', 'death', 'refugees', 'money', 'security', 'military', 'clothing', 
           'tools', 'missing_people', 'child_alone', 'search_and_rescue', 'medical_help', 'medical_products', 
           'aid_centers', 'other_aid']

weather_lst = ['earthquake', 'storm', 'floods', 'fire', 'cold', 'other_weather']

infrastructure_lst = ['buildings', 'transport', 'hospitals', 'electricity', 'shops', 'other_infrastructure']

To concatenate lists:

In [22]:
a = ['a', 'b']
b = ['c', 'd']
a+b

['a', 'b', 'c', 'd']

Inserting the concept into our project:
    
- `fn_count_valids` created

In [23]:
expand_list = expand_lst + aid_lst + weather_lst + infrastructure_lst

verbose = False
total = df.shape[0]
counts = []

for field in expand_list:
    count = udacourse2.fn_count_valids(dataset=df, field=field)
    percent = 100. * (count / total)
    counts.append((count, field, percent))
    if verbose:
        print('{}:{} ({:.1f}%)'.format(field, count, percent))

Order Tupples [here](https://www.pythoncentral.io/how-to-sort-a-list-tuple-or-object-with-sorted-in-python/):

- i will need it to create an **ordered report** about labels

In [24]:
sorted_tuples = sorted(counts, key=udacourse2.fn_getKey, reverse=True)

i=1
c=2
max_c=3

for cat in sorted_tuples:
    count, field, percent = cat
    print('{}-{}:{} ({:.1f}%)'.format(i, field, count, percent))
    if c > max_c:
        break
    else:
        i += 1
        c += 1

1-related:19928 (75.9%)
2-aid_related:10877 (41.4%)
3-weather_related:7304 (27.8%)


Turning this into a function:

- `fn_labels_report`created

In [45]:
udacourse2.fn_labels_report(dataset=df, 
                            max_c=10)

1-related:19928 (75.9%)
2-aid_related:10903 (41.5%)
3-weather_related:7304 (27.8%)
4-direct_report:5080 (19.4%)
5-request:4480 (17.1%)
6-other_aid:3448 (13.1%)
7-food:2930 (11.2%)
8-earthquake:2455 (9.4%)
9-storm:2448 (9.3%)
10-shelter:2319 (8.8%)


---

#### Some studies about labels

*OK, I already know that **labels** are not **features**... but we may do some **critics** about the labels that exists for multi-classification*

Strong candidates labels candidates for **ignoring**:
    
>- **related** (75.0%) $\rightarrow$ too **weighty** and looks **meaningless**
>- **child_alone** (empty) $\rightarrow$ **impossible to train**, as it don´t have any valid element in the dataset
>- **request** (17.1%), **offer** (0.4%) **direct_report** (19.4%) $\rightarrow$ looks **meaningless**

---

#### Another viewpoint about these labels

If we look at them more carefully, we can find a curious pattern on them

These labels looks as they have a kind of hierarchy behind their shape, as:

First **hierarchical** class: 

>- **related**
>- **request**
>- **offer**
>- **direct_report**

And then, **related** seems to have a **Second** hierarchical class

Features for considering a training a classifier on **two layes**, or to **group** them all in main groups, as they are clearly **collinear**:

>- **aid_related** $\rightarrow$ groups aid calling (new things to add/ to do **after** the disaster)
>>- **food**
>>- **shelter**
>>- **water**
>>- **death**
>>- **refugees**
>>- **money**
>>- **security**
>>- **military**
>>- **clothing**
>>- **tools**
>>- **missing_people**
>>- **child_alone**
>>- **search_and_rescue**
>>- **medical_help**
>>- **medical_products**
>>- **aid_centers**
>>- **other_aid**
>- **weather_related** $\rightarrow$ groups what was the main **cause** of the disaster
>>- **earthquake**
>>- **storm**
>>- **floods**
>>- **fire**
>>- **cold**
>>- **other_weather**
>- **infrastructure_related** $\rightarrow$ groups **heavy infra** that was probably dammaged during the disaster
>>- **buildings**
>>- **transport**
>>- **hospitals**
>>- **electricity**
>>- **shops**
>>- **other_infrastructure**

Let´s filter & count for one **subcategory**:

In [26]:
df[df['food'] == 1].shape[0]

2930

Trying to have a union of two subcategories:

- how to make multifilters [here](https://stackoverflow.com/questions/13611065/efficient-way-to-apply-multiple-filters-to-pandas-dataframe-or-series)

- first trying two categories + **OR** clause

In [27]:
df[(df['food'] == 1) ^ (df['shelter'] == 1)].shape[0]

3659

Turning into a more automatized mode

In [28]:
a = "(df['food'] == 1) ^ (df['shelter'] == 1)"

df[eval(a)].shape[0]

3659

Preparing to turn it into a function

- `fn_cat_condenser` created

In [29]:
cat_aid_related = aid_lst
dataset = 'df'
element = '1'
opperator = '=='
condition = '^'
string = ''

for item in cat_aid_related:
    string = string + "(" + dataset + "['" + item + "'] " + opperator + " " + element + ")" + " " + condition + " "
    
string[:-3]

"(df['food'] == 1) ^ (df['shelter'] == 1) ^ (df['water'] == 1) ^ (df['death'] == 1) ^ (df['refugees'] == 1) ^ (df['money'] == 1) ^ (df['security'] == 1) ^ (df['military'] == 1) ^ (df['clothing'] == 1) ^ (df['tools'] == 1) ^ (df['missing_people'] == 1) ^ (df['child_alone'] == 1) ^ (df['search_and_rescue'] == 1) ^ (df['medical_help'] == 1) ^ (df['medical_products'] == 1) ^ (df['aid_centers'] == 1) ^ (df['other_aid'] == 1)"

---

### Tests for class `aid_related` 

Counting for the main class **aid_related**:
    
- you can see that **aid_related** have more rows registered than all subclasses counted together

- this is not about training a **Machine Learning**, this is about **database data consistency**

*Just think in this way: if something is labelled as **aid_related**, so every data under it may be contained by **aid_related**. So next step, we need to correct this thing, turning **aid_related = 1** for all of them*

In [30]:
df_aid_main = df[df['aid_related'] == 1]
df_aid_main.shape[0]

10877

Filtering for **main**, without any **sub-category** registered:

- this is **empty data** as the main category is checked, but the subcategory is not!

In [31]:
#fn_cat_condenser(subset='aid', opperation='main_not_sub')

In [32]:
main_not_sub = df[eval(udacourse2.fn_cat_condenser(subset='aid', 
                                                   name='df',
                                                   opperation='main_not_sub')[0])]
main_not_sub.shape[0]

3515

Testing the function for grouping all **subclasses**

- counting for all subclasses of **aid_related*

- filtering for all **subcategories** with any register:

In [33]:
#fn_cat_condenser(subset='aid', opperation='all_sub')

In [34]:
all_aid_subsets = df[eval(udacourse2.fn_cat_condenser(subset='aid',
                                                      name='df',
                                                      opperation='all_sub')[0])]
all_aid_subsets.shape[0]

7388

Filtering for **all empty** subcategories:

In [35]:
#fn_cat_condenser(subset='aid', opperation='sub_not_main')

In [36]:
sub_not_main = df[eval(udacourse2.fn_cat_condenser(subset='aid',
                                                   name='df',
                                                   opperation='empty_sub')[0])]
sub_not_main.shape[0]

0

---

#### Inconsistency detected

1. Just consider that our **labels** have a kind of **hierarchical structure**

2. Before running a Machine Learning **Classifier**, we can procede some **mechanical opperations** for correcting database **data inconsistencies**

3. The theoretical support for this opperations resides on **database theory** (e.g. if something is a subclass of other thing, so, the class must be setted on for each of the rows that are setted for at least one item of the subclass) 



Filtering for **empty main** with any **subcategory** registered:

>- this is a **database inconsistency** 
>- as if a **subgroup** is valid, so the **main** group must be valid too!
>- about database **normal forms**, please read [here](https://www.guru99.com/database-normalization.html)

In [37]:
#fn_cat_condenser(subset='aid', opperation='sub_not_main')

In [38]:
sub_not_main = df[eval(udacourse2.fn_cat_condenser(subset='aid',
                                                   name='df',
                                                   opperation='sub_not_main')[0])]
sub_not_main.shape[0]

26

Correcting our **data inconsistency**:

>- considering `opp` is only a **filter** for columns that have any value in sublabels
>- `df[eval(opp[0])]` gives our dataset rows for this filter
>- `df[eval(opp[0])].index` is only about the address to find these rows
>- finally, we need to correct `opp[1]]`, that is the name of the column, by the value `1`

In [39]:
opp = udacourse2.fn_cat_condenser(subset='aid',
                                  name='df',
                                  opperation='sub_not_main')

#df[eval(opp[0])]
#df.loc[df[eval(opp[0])].index, opp[1]] = 1 #I don´t want to correct it now!

sub_not_main = df[eval(udacourse2.fn_cat_condenser(subset='aid', opperation='sub_not_main')[0])]
sub_not_main.shape[0]

26

Turning this into a function

- function `fn_croup_check` created

In [40]:
df_aid = udacourse2.fn_group_check(dataset=df,
                                   subset='aid',
                                   correct=True, 
                                   shrink=True, 
                                   shorten=True, 
                                   verbose=True)
df_aid.head(5)

###function group_check started
  - count for main class:aid_related, 10877 entries
  - for main, without any sub-categories,  3515 entries
  - for subcategories,  7388 entries
  - for lost parent sub-categories,  26 entries
    *correcting, new count: 0 entries
    *shrinking, dataset now have: 21 columns
    *shortening, dataset now have: 10903 lines
elapsed time: 0.1129s


message   genre  if_blank  \
id                                                                        
7             Is the Hurricane over or is it not over  direct     False   
9   UN reports Leogane 80-90 destroyed. Only Hospi...  direct     False   
16  Please, we need tents and water. We are in Sil...  direct     False   
18  I am in Croix-des-Bouquets. We have health iss...  direct     False   
20  There's nothing to eat and water, we starving ...  direct     False   

    aid_related  food  shelter  water  death  refugees  money  ...  military  \
id                                                             ...             
7             1     0        0      0      0         0      0  ...         0   
9             1     0        0      0      0         0      0  ...         0   
16            1     0        1      1      0         0      0  ...         0   
18            1     0        0      0      0         0      0  ...         0   
20            1     1        0      1      0         0      0  ...         0   

    clothing  tools  missing_people  child_alone  search_and_rescue  \
id                                                                    
7          0      0               0            0                  0   
9          0      0               0            0                  0   
16         0      0               0            0                  0   
18         0      0               0            0                  0   
20         0      0               0            0                  0   

    medical_help  medical_products  aid_centers  other_aid  
id                                                          
7              0                 0            0          1  
9              0                 1            0          1  
16             0                 0            0          0  
18             1                 1            0          0  
20             1                 1            0          1  

[5 rows x 21 columns]

---

### About rows:
    
- We have 40 columns, and some rows that cannot be used to **train** any model (all their features are blank)

All the dataframe:

In [41]:
df.shape[0]

26245

Blank labels:
    
- it's not a good idea training with this data;

- they have **zero** classification (no labels at all!)

In [42]:
df[df['if_blank']].shape[0]

6317

Labels with some content:

In [43]:
df[~df['if_blank']].shape[0]

19928

---

## Test area (can be removed later)

In [44]:
raise Exception('Test area')

Exception: Test area

In [ ]:
full_path = 'c://host/pyprog/project/udacourse/categories.csv'
full_path = 'c://host/pyprog/project/udacourse/messages.csv'
last_one = full_path.rfind('/')
full_path[last_one+1:-4]

In [ ]:
categories.index.name = 'categories'
categories.index.name

In [ ]:
uma = 0.70
duas = 0.305
primeira = 0.35 #0.51
segunda = 0.67 #0.74

delta = ((uma - duas) * primeira) + (duas * segunda)
delta

In [ ]:
uma = 0.70
duas = 0.305
primeira = 0.70
segunda = 0.88

original = ((uma - duas) * primeira) + (duas * segunda)
original

In [ ]:
primeira = 0.51
segunda = 0.74

alfa = ((uma - duas) * primeira) + (duas * segunda)
alfa

In [ ]:
def fn_teste(dataset):
    #print(dataset.iloc[0])
    print(locals())

In [ ]:
fn_teste(dataset=df)